CREATE TABLE BookFiles(
	Id INT IDENTITY PRIMARY KEY,
	BookId INT,
	BookCover VARBINARY(MAX),
	FilePath VARCHAR(255) NOT NULL,
	FileType VARCHAR(50) NOT NULL,
	UploadDate DATETIME DEFAULT GETDATE(),
	Foreign KEY (BookId) REFERENCES Books(Id)
)